export const consignmentListResponse = {
  completedShipments: [
    {
      SHIPMENTID: "INGLO-100186",
      INLOPSID: "IPL210624_0148",
      CARGOWISEID: "SSE0624001580",
      SCACCODE: "HLCU",
      BOOKINGNUMBER: "21843935",
      BILLOFLADING: "HLCUBO12406BFYA5",
      CONTAINERID: "HAMU1790389",
      CONTAINERQUANTITY: "NaN",
      CONSIGNEENAME: "TRADE PARTNERS",
      COMMERCIALINVOICE: "EXP/030/2024-",
      DELIVERYMODE: "Ocean",
      FREIGHTCLASS: "FCL",
      TOTALDEADWEIGHT: 24890,
      TOTALDEADWEIGHTMETRIC: "kg",
      SHIPMENTSTATUS: "Completed",
      SHIPPEDBY: null,
      VESSELNAME: ["EXPRESS ATHENS"],
      VOYAGE: ["4126"],
      ESTIMATEDDELIVERYDATE: "2024-08-06 15:01:00",
      LASTSTATUSUPATEDON: "2024-09-29 11:16:25",
      LOCATIONS: [
        {
          LOCATIONTYPE: "POL",
          LOCATIONNAME: "Jawaharlal Nehru (Nhava Sheva)",
          COUNTRY: "India",
        },
        {
          LOCATIONTYPE: "POD",
          LOCATIONNAME: "New York",
          COUNTRY: "United States",
        },
      ],
      LASTCOMPLETEDEVENT: "Gate in empty return",
      LASTCOMPLETEDEVENTDATETIME: "2024-08-06 15:01:00",
      LASTCOMPLETEDEVENTLOCATION: {
        LOCATIONNAME: "New York",
        COUNTRY: "United States",
      },
      ACTUALDELIVERYDATE: "2024-08-06 15:01:00",
      ISBOOKMARKED: false,
    },
    {
      SHIPMENTID: "INGLO-100188",
      INLOPSID: "IPL220624_0154",
      CARGOWISEID: "SSE0724001588",
      SCACCODE: "HLCU",
      BOOKINGNUMBER: "67955737",
      BILLOFLADING: "HLCUBO12406CLPJ5",
      CONTAINERID: "BMOU4648204",
      CONTAINERQUANTITY: "NaN",
      CONSIGNEENAME: "TRADE PARTNERS",
      COMMERCIALINVOICE: "EXP/031/2024-25",
      DELIVERYMODE: "Ocean",
      FREIGHTCLASS: "FCL",
      TOTALDEADWEIGHT: 27128,
      TOTALDEADWEIGHTMETRIC: "kg",
      SHIPMENTSTATUS: "Completed",
      SHIPPEDBY: null,
      VESSELNAME: ["TENO"],
      VOYAGE: ["4127"],
      ESTIMATEDDELIVERYDATE: "2024-08-20 14:30:00",
      LASTSTATUSUPATEDON: "2024-09-29 11:15:27",
      LOCATIONS: [
        {
          LOCATIONTYPE: "POL",
          LOCATIONNAME: "Jawaharlal Nehru (Nhava Sheva)",
          COUNTRY: "India",
        },
        {
          LOCATIONTYPE: "POD",
          LOCATIONNAME: "New York",
          COUNTRY: "United States",
        },
      ],
      LASTCOMPLETEDEVENT: "Gate in empty return",
      LASTCOMPLETEDEVENTDATETIME: "2024-08-20 14:30:00",
      LASTCOMPLETEDEVENTLOCATION: {
        LOCATIONNAME: "New York",
        COUNTRY: "United States",
      },
      ACTUALDELIVERYDATE: "2024-08-20 14:30:00",
      ISBOOKMARKED: false,
    },
    {
      SHIPMENTID: "INGLO-100201",
      INLOPSID: "SEINUS27072400280_I",
      CARGOWISEID: "SSE0724001644",
      SCACCODE: "HLCU",
      BOOKINGNUMBER: "92055892",
      BILLOFLADING: "HLCUBO12407CBTH3",
      CONTAINERID: "GCXU5164102",
      CONTAINERQUANTITY: "NaN",
      CONSIGNEENAME: "TRADE PARTNERS",
      COMMERCIALINVOICE: "EXP/032/2024-25",
      DELIVERYMODE: "Ocean",
      FREIGHTCLASS: "FCL",
      TOTALDEADWEIGHT: 23138,
      TOTALDEADWEIGHTMETRIC: "kg",
      SHIPMENTSTATUS: "Completed",
      SHIPPEDBY: {
        LINERNAME: "Hapag-Lloyd",
        TRACKINGLINK:
          "https://www.hapag-lloyd.com/en/online-business/track/track-by-container-solution.html",
      },
      VESSELNAME: ["TORRENTE"],
      VOYAGE: ["4132"],
      ESTIMATEDDELIVERYDATE: "2024-09-19 17:31:00",
      LASTSTATUSUPATEDON: "2024-10-02 19:44:35",
      LOCATIONS: [
        {
          LOCATIONTYPE: "POL",
          LOCATIONNAME: "Jawaharlal Nehru (Nhava Sheva)",
          COUNTRY: "India",
        },
        {
          LOCATIONTYPE: "POD",
          LOCATIONNAME: "New York",
          COUNTRY: "United States",
        },
      ],
      LASTCOMPLETEDEVENT: "Gate in empty",
      LASTCOMPLETEDEVENTDATETIME: "2024-09-19 17:31:00",
      LASTCOMPLETEDEVENTLOCATION: {
        LOCATIONNAME: "Newark",
        COUNTRY: "United States",
      },
      ACTUALDELIVERYDATE: "2024-09-19 17:31:00",
      ISBOOKMARKED: false,
    },
    {
      SHIPMENTID: "INGLO-100265",
      INLOPSID: "SEINUS13092400539",
      CARGOWISEID: "SSE0924001720",
      SCACCODE: "CMDU",
      BOOKINGNUMBER: null,
      BILLOFLADING: "AMC2295073",
      CONTAINERID: "SEKU6489891",
      CONTAINERQUANTITY: "NaN",
      CONSIGNEENAME: "RISHABH99",
      COMMERCIALINVOICE: "EXP/035/2024-25",
      DELIVERYMODE: "Ocean",
      FREIGHTCLASS: "FCL",
      TOTALDEADWEIGHT: 23910,
      TOTALDEADWEIGHTMETRIC: "kg",
      SHIPMENTSTATUS: "Completed",
      SHIPPEDBY: {
        LINERNAME: "CMA-CGM",
        TRACKINGLINK: "https://www.cma-cgm.com/ebusiness/tracking/search",
      },
      VESSELNAME: ["LOTUS A"],
      VOYAGE: ["0INHXW1MA", "0INHYE1MA"],
      ESTIMATEDDELIVERYDATE: "2024-11-11 13:41:00",
      LASTSTATUSUPATEDON: "2024-11-12 13:32:35",
      LOCATIONS: [
        {
          LOCATIONTYPE: "POL",
          LOCATIONNAME: "Jawaharlal Nehru (Nhava Sheva)",
          COUNTRY: "India",
        },
        {
          LOCATIONTYPE: "POD",
          LOCATIONNAME: "Chicago",
          COUNTRY: "United States",
        },
      ],
      LASTCOMPLETEDEVENT: "Gate in empty",
      LASTCOMPLETEDEVENTDATETIME: "2024-11-11 13:41:00",
      LASTCOMPLETEDEVENTLOCATION: {
        LOCATIONNAME: "Chicago",
        COUNTRY: "United States",
      },
      ACTUALDELIVERYDATE: "2024-11-11 13:41:00",
      ISBOOKMARKED: true,
    },
    {
      SHIPMENTID: "INGLO-100317",
      INLOPSID: "SEINUS17092400558_I",
      CARGOWISEID: "SSE0924001735",
      SCACCODE: "MAEU",
      BOOKINGNUMBER: null,
      BILLOFLADING: "244653024",
      CONTAINERID: "MRSU4709475",
      CONTAINERQUANTITY: "NaN",
      CONSIGNEENAME: "RISHABH99",
      COMMERCIALINVOICE: "EXP/037&38&41",
      DELIVERYMODE: "Ocean",
      FREIGHTCLASS: "FCL",
      TOTALDEADWEIGHT: 75443.25,
      TOTALDEADWEIGHTMETRIC: "kg",
      SHIPMENTSTATUS: "Completed",
      SHIPPEDBY: {
        LINERNAME: "Maersk",
        TRACKINGLINK: "https://www.maersk.com/tracking/",
      },
      VESSELNAME: ["MAERSK CHICAGO"],
      VOYAGE: ["438W"],
      ESTIMATEDDELIVERYDATE: "2024-11-08 10:24:00",
      LASTSTATUSUPATEDON: "2024-11-09 05:46:38",
      LOCATIONS: [
        {
          LOCATIONTYPE: "POL",
          LOCATIONNAME: "Jawaharlal Nehru (Nhava Sheva)",
          COUNTRY: "India",
        },
        {
          LOCATIONTYPE: "POD",
          LOCATIONNAME: "Newark",
          COUNTRY: "United States",
        },
      ],
      LASTCOMPLETEDEVENT: "Gate in empty",
      LASTCOMPLETEDEVENTDATETIME: "2024-11-08 10:24:00",
      LASTCOMPLETEDEVENTLOCATION: {
        LOCATIONNAME: "Newark",
        COUNTRY: "United States",
      },
      ACTUALDELIVERYDATE: "2024-11-08 10:24:00",
      ISBOOKMARKED: false,
    },
  ],
  inTransitShipments: [
    {
      SHIPMENTID: "INGLO-100276",
      INLOPSID: "SEINUS17092400558_I",
      CARGOWISEID: "SSE0924001735",
      SCACCODE: "MAEU",
      BOOKINGNUMBER: null,
      BILLOFLADING: "244653024",
      CONTAINERID: "SUDU6904977",
      CONTAINERQUANTITY: "NaN",
      CONSIGNEENAME: "RISHABH99",
      COMMERCIALINVOICE: "EXP/037&38&41",
      DELIVERYMODE: "Ocean",
      FREIGHTCLASS: "FCL",
      TOTALDEADWEIGHT: 75443.25,
      TOTALDEADWEIGHTMETRIC: "kg",
      SHIPMENTSTATUS: "In Transit",
      SHIPPEDBY: {
        LINERNAME: "Maersk",
        TRACKINGLINK: "https://www.maersk.com/tracking/",
      },
      VESSELNAME: ["MAERSK CHICAGO"],
      VOYAGE: ["438W"],
      ESTIMATEDDELIVERYDATE: "2024-11-15 15:29:00",
      LASTSTATUSUPATEDON: "2024-11-13 05:40:41",
      LOCATIONS: [
        {
          LOCATIONTYPE: "POL",
          LOCATIONNAME: "Jawaharlal Nehru (Nhava Sheva)",
          COUNTRY: "India",
        },
        {
          LOCATIONTYPE: "POD",
          LOCATIONNAME: "Newark",
          COUNTRY: "United States",
        },
      ],
      LASTCOMPLETEDEVENT: "Gate out from destination port",
      LASTCOMPLETEDEVENTDATETIME: "2024-11-11 15:29:00",
      LASTCOMPLETEDEVENTLOCATION: {
        LOCATIONNAME: "Newark",
        COUNTRY: "United States",
      },
      ISBOOKMARKED: false,
    },
    {
      SHIPMENTID: "INGLO-100277",
      INLOPSID: "SEINUS17092400559_I",
      CARGOWISEID: "SSE0924001736",
      SCACCODE: "MAEU",
      BOOKINGNUMBER: null,
      BILLOFLADING: "244653226",
      CONTAINERID: "PONU7872628",
      CONTAINERQUANTITY: "NaN",
      CONSIGNEENAME: "RISHABH99",
      COMMERCIALINVOICE: "EXP/039 & 40",
      DELIVERYMODE: "Ocean",
      FREIGHTCLASS: "FCL",
      TOTALDEADWEIGHT: 47173.2,
      TOTALDEADWEIGHTMETRIC: "kg",
      SHIPMENTSTATUS: "In Transit",
      SHIPPEDBY: {
        LINERNAME: "Maersk",
        TRACKINGLINK: "https://www.maersk.com/tracking/",
      },
      VESSELNAME: ["MAERSK CHICAGO"],
      VOYAGE: ["438W"],
      ESTIMATEDDELIVERYDATE: "2024-11-14 07:50:00",
      LASTSTATUSUPATEDON: "2024-11-11 05:02:39",
      LOCATIONS: [
        {
          LOCATIONTYPE: "POL",
          LOCATIONNAME: "Jawaharlal Nehru (Nhava Sheva)",
          COUNTRY: "India",
        },
        {
          LOCATIONTYPE: "POD",
          LOCATIONNAME: "Newark",
          COUNTRY: "United States",
        },
      ],
      LASTCOMPLETEDEVENT: "Loaded on rail",
      LASTCOMPLETEDEVENTDATETIME: "2024-11-10 07:50:00",
      LASTCOMPLETEDEVENTLOCATION: {
        LOCATIONNAME: "Syracuse",
        COUNTRY: "United States",
      },
      ISBOOKMARKED: true,
    },
    {
      SHIPMENTID: "INGLO-100316",
      INLOPSID: "SEINUS17092400558_I",
      CARGOWISEID: "SSE0924001735",
      SCACCODE: "MAEU",
      BOOKINGNUMBER: null,
      BILLOFLADING: "244653024",
      CONTAINERID: "TCKU6517645",
      CONTAINERQUANTITY: "NaN",
      CONSIGNEENAME: "RISHABH99",
      COMMERCIALINVOICE: "EXP/037&38&41",
      DELIVERYMODE: "Ocean",
      FREIGHTCLASS: "FCL",
      TOTALDEADWEIGHT: 75443.25,
      TOTALDEADWEIGHTMETRIC: "kg",
      SHIPMENTSTATUS: "In Transit",
      SHIPPEDBY: {
        LINERNAME: "Maersk",
        TRACKINGLINK: "https://www.maersk.com/tracking/",
      },
      VESSELNAME: ["MAERSK CHICAGO"],
      VOYAGE: ["438W"],
      ESTIMATEDDELIVERYDATE: "2024-11-15 07:58:00",
      LASTSTATUSUPATEDON: "2024-11-13 05:34:37",
      LOCATIONS: [
        {
          LOCATIONTYPE: "POL",
          LOCATIONNAME: "Jawaharlal Nehru (Nhava Sheva)",
          COUNTRY: "India",
        },
        {
          LOCATIONTYPE: "POD",
          LOCATIONNAME: "Newark",
          COUNTRY: "United States",
        },
      ],
      LASTCOMPLETEDEVENT: "Gate out from destination port",
      LASTCOMPLETEDEVENTDATETIME: "2024-11-11 07:58:00",
      LASTCOMPLETEDEVENTLOCATION: {
        LOCATIONNAME: "Newark",
        COUNTRY: "United States",
      },
      ISBOOKMARKED: false,
    },
    {
      SHIPMENTID: "INGLO-100318",
      INLOPSID: "SEINUS17092400559_I",
      CARGOWISEID: "SSE0924001736",
      SCACCODE: "MAEU",
      BOOKINGNUMBER: null,
      BILLOFLADING: "244653226",
      CONTAINERID: "TCKU7201970",
      CONTAINERQUANTITY: "NaN",
      CONSIGNEENAME: "RISHABH99",
      COMMERCIALINVOICE: "EXP/039 & 40",
      DELIVERYMODE: "Ocean",
      FREIGHTCLASS: "FCL",
      TOTALDEADWEIGHT: 47173.2,
      TOTALDEADWEIGHTMETRIC: "kg",
      SHIPMENTSTATUS: "In Transit",
      SHIPPEDBY: {
        LINERNAME: "Maersk",
        TRACKINGLINK: "https://www.maersk.com/tracking/",
      },
      VESSELNAME: ["MAERSK CHICAGO"],
      VOYAGE: ["438W"],
      ESTIMATEDDELIVERYDATE: "2024-11-16 13:14:00",
      LASTSTATUSUPATEDON: "2024-11-13 05:38:36",
      LOCATIONS: [
        {
          LOCATIONTYPE: "POL",
          LOCATIONNAME: "Jawaharlal Nehru (Nhava Sheva)",
          COUNTRY: "India",
        },
        {
          LOCATIONTYPE: "POD",
          LOCATIONNAME: "Newark",
          COUNTRY: "United States",
        },
      ],
      LASTCOMPLETEDEVENT: "Gate out full",
      LASTCOMPLETEDEVENTDATETIME: "2024-11-12 13:14:00",
      LASTCOMPLETEDEVENTLOCATION: {
        LOCATIONNAME: "Chicago",
        COUNTRY: "United States",
      },
      ISBOOKMARKED: false,
    },
  ],
};
